name: link_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
    
  table_calendar: ^3.0.9
  go_router: ^16.2.2
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0
  riverpod_generator: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
